export default function Loader() {
    return (
        <div className="loadingio-spinner-dual-ball-n768zk6dlij mt-5"><div className="ldio-g4sv7rq6nrw">
            <div></div><div></div><div></div>
        </div></div>
    )
}

/* generated by https://loading.io/ */